#!/usr/bin/env python3
"""Mirror the live rating aggregates into _data/ratings-live.yml.

The site's own ratings are in D1, behind the Worker's /api/ratings, which answers
with every slug that has at least one live rating:

    {"generated_at": "2026-09-06T00:00:00Z",
     "product": {"achromic": {"count": 7, "average": 4.2857}}}

This writes that into the data file the badge reads at build time, so the figure
is in the HTML the moment the page is — nothing is fetched at runtime, and
nothing on the page can come up empty. Run by .github/workflows/ratings.yml once
an hour.

The mirror moves data and nothing else: the display rule (a blended average of
4.0 or more, exact rather than rounded) lives in _includes/product-rating.html
and nowhere here. Failure is soft on purpose — a non-200, a timeout or an
unparseable body leaves the file exactly as it was and only warns, so a Worker
blip cannot blank a badge that was fine.

    python scripts/mirror_ratings.py
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "_data" / "ratings-live.yml"

# The same workers.dev host as contact_endpoint in _config.yml, on the Worker's
# aggregate route.
ENDPOINT = "https://iamlamprey-contact.iamlamprey.workers.dev/api/ratings"
TIMEOUT = 30

HEADER = """# Generated by .github/workflows/ratings.yml — do not edit by hand.
#
# This site's own ratings, mirrored from the Worker's /api/ratings. They are
# pooled with the marketplace figures in ratings.yml rather than replacing them:
# _includes/product-rating.html sums the two counts and weights the average by
# those counts, so a single live rating is enough to render a badge. Every
# rating counts, including the low ones, and the display rule is there rather
# than here."""


def warn(message: str) -> None:

    # a github annotation, so a soft failure still shows up in the run

    print(f"::warning::{message}")
    print(f"warning: {message}", file=sys.stderr)


def fetch(endpoint: str):
    # the aggregates, or None when the response is not one we can use

    try:
        response = requests.get(endpoint, timeout=TIMEOUT)
    except requests.exceptions.RequestException as error:
        warn(f"could not read {endpoint}: {error}")
        return None

    if response.status_code != 200:
        warn(f"{endpoint} returned HTTP {response.status_code}")
        return None

    try:
        payload = response.json()
    except ValueError as error:
        warn(f"{endpoint} did not return json: {error}")
        return None

    if not isinstance(payload, dict) or not isinstance(payload.get("product"), dict):
        warn(f"{endpoint} returned an unexpected shape")
        return None

    return payload


def clean_product(payload: dict):
    # the slug -> {average, count} map, or None when any row cannot be trusted:
    # a figure that cannot be used must not replace one that can

    product = payload.get("product") or {}
    cleaned = {}

    for slug, row in product.items():
        if not isinstance(row, dict):
            warn(f"{slug!r} is not a rating row")
            return None

        try:
            cleaned[str(slug)] = {"average": float(row["average"]), "count": int(row["count"])}
        except (KeyError, TypeError, ValueError) as error:
            warn(f"{slug!r} carries an unusable figure: {error}")
            return None

    return cleaned


def format_average(value: float) -> str:
    # four decimal places at most, and always a decimal point: the badge caption
    # rounds the figure, and Liquid prints 4 as "4" where it prints 4.0 as "4.0"

    text = f"{value:.4f}".rstrip("0")

    return text + "0" if text.endswith(".") else text


def body(product: dict) -> str:
    # the product block, one slug per line, sorted. The sort is what keeps an
    # unchanged mirror from rewriting the file — and committing — every hour.

    lines = ["product:"]

    for slug in sorted(product):
        row = product[slug]
        lines.append(f"  {slug}: {{ average: {format_average(row['average'])}, count: {row['count']} }}")

    return "\n".join(lines)


def product_block(text: str) -> str:
    # the product block of a data file, so a new mirror can be compared with it

    lines = text.replace("\r\n", "\n").split("\n")

    for index, line in enumerate(lines):
        if line.startswith("product:"):
            return "\n".join(lines[index:]).strip()

    return ""


def main() -> int:

    payload = fetch(ENDPOINT)
    if payload is not None:
        product = clean_product(payload)
    else:
        product = None

    if product is None:
        print(f"leaving {OUTPUT.name} as it is")
        return 0

    mirrored = body(product)

    # generated_at dates the figures rather than the run, so a run that changes
    # nothing leaves the file — and the stamp — alone
    if OUTPUT.exists() and product_block(OUTPUT.read_text(encoding="utf-8")) == mirrored:
        print(f"{OUTPUT.name}: no change")
        return 0

    generated_at = str(payload.get("generated_at") or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))
    OUTPUT.write_text(f"{HEADER}\ngenerated_at: {generated_at}\n{mirrored}\n", encoding="utf-8", newline="\r\n")

    print(f"{OUTPUT.name}: {len(product)} product(s) at {generated_at}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
